### ISSUE TITLE
could you please attach the data using in the r script, thanks.

### ISSUE THREAD

**Issue by ghost** [hxnx-sam/Rcode_utils#1]
In the R scripts, I could not find the data in these r scripts, so I can not reproduce the results, could you please attach them, thanks.

**Comment by hxnx-sam** [comment]
Dear lixingguang - the scripts here (there are several) are utility scripts which are often useful (for me anyway) in processing various sequence and tree data in R. But they are not intended to be used standalone.  The data I would typically use them with are based on influenza sequence data from Genbank (NCBI Influenza virus database) with the following sequence name definition for fasta nucleotide downloads:
>{serotype}_{host}_{accession}_{strain}_{country}_{year}/{month}/{day}_{segname}
